export const variants = {
  geniesPokemon: ["tornadus", "thundurus", "landorus", "enamorus"],
  rotomForms: [
    "rotom-heat",
    "rotom-wash",
    "rotom-frost",
    "rotom-fan",
    "rotom-mow",
  ],
  urshifu: ["urshifu-single-strike", "urshifu-rapid-strike"],
  regionalForms: {
    rattata: "rattata-alola",
    raticate: "raticate-alola",
    raichu: "raichu-alola",
    sandshrew: "sandshrew-alola",
    sandslash: "sandslash-alola",
    vulpix: "vulpix-alola",
    ninetales: "ninetales-alola",
    diglett: "diglett-alola",
    dugtrio: "dugtrio-alolla",
    meowth: "meowth-alola/meowth-galar",
    persian: "persian-alola",
    growlithe: "growlithe-hisui",
    arcanine: "arcanine-hisui",
    geodude: "geodude-alola",
    graveler: "graveler-alola",
    golem: "golem-alola",
    ponyta: "ponyta-galar",
    rapidash: "rapidash-galar",
    slowpoke: "slowpoke-galar",
    slowbro: "slowbro-galar",
    farfetchd: "farfetchd-galar",
    grimer: "grimer-alola",
    muk: "muk-alola",
    voltorb: "voltorb-hisui",
    electrode: "electrode-hisui",
    exeggutor: "exeggutor-alola",
    marowak: "marowak-alola",
    weezing: "weezing-galar",
    "mr-mime": "mr-mime-galar",
    articuno: "articuno-galar",
    zapdos: "zapdos-galar",
    moltres: "moltres-galar",
    typhlosion: "typhlosion-hisui",
    wooper: "wooper-paldea",
    slowking: "slowking-galar",
    qwilfish: "qwilfish-hisui",
    corsola: "corsola-galar",
    sneasel: "sneasel-hisui",
    zigzagoon: "zigzagoon-galar",
    linoone: "linoone-galar",
    samurott: "samurott-hisui",
    lilligant: "lilligant-hisui",
    darumaka: "darumaka-galar",
    yamask: "yamask-galar",
    zorua: "zorua-hisui",
    zoroark: "zoroark-hisui",
    stunfisk: "stunfisk-galar",
    braviary: "braviary-hisui",
    sliggoo: "sliggoo-hisui",
    goodra: "goodra-hisui",
    avalugg: "avalugg-hisui",
    decidueye: "decidueye-hisui",
    tauros:
      "tauros-paldea-combat-breed/tauros-paldea-blaze-breed/tauros-paldea-aqua-breed",
    basculin:
      "basculin-red-striped/basculin-blue-striped/basculin-white-striped",
  },
  darmanitan: [
    "darmanitan-standard",
    "darmanitan-zen",
    "darmanitan-galar-standard",
    "darmanitan-galar-zen",
  ],
};
